language: python
python:
        - "3.5"
install:
        - sudo apt-get update
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install nbformat
        - conda info -a
        - conda info --envs
        - conda env export -n HetMan
        - conda env create -n HetMan
        - source activate HetMan

script: pytest -vv test_hetman.py

